### ISSUE TITLE
Some fixes

### ISSUE THREAD

**Issue by jklukas** [scholtzan/python-udf-bigquery#1]
I tried running through the instructions and found the following small issues:

  - The instructions for running don't include installing libraries. I had to `pip install gcloud` and it may be a good idea to suggest created a virtualenv in the instructions:

```
python3 -m venv venv
source venv/bin/activate
pip install gcloud
```

- The output query does not have the library paths enclosed in quotes.
- The output query's list of library paths has a trailing comma that is not allowed in BQ syntax.

Also, it would be convenient to make the JS files in GCS public and provide an invocation that references that bucket so that you can follow the instructions and get a complete working example.

**Comment by scholtzan** [comment]
Thanks! I fixed the issues and updated `README`.
